#!/usr/bin/env python3
# coding=UTF-8

from sys import argv
from core import eprint, calculate

import os

def display_help():
    """ Help output printer """
    print("USAGE")
    print("\t./204ducks a")
    print("\nDESCRIPTION")
    print("\ta\tconstant")


def main():
    argc = len(argv)
    if argc == 2:
        if argv[1] == "-h" or argv[1] == "--help":
            display_help()
            return 0
        elif argv[1] == "-t" or argv[1] == "--tests":
            return os.system("./tests.py -v")
        nb = 0
        try:
            nb = float(argv[1])
        except Exception as e:
            eprint(str(e).capitalize())
        if nb < 0.0 or nb > 2.5:
            eprint("Constant a must be a number between 0 and 2.5")
        calculate(nb)
    else:
        eprint("Bad number of argument")
    return 0


if __name__ == '__main__':
    main()
